name: LerixExample
options:
  bundleIdPrefix: dev.atelerix
  deploymentTarget:
    iOS: "13.0"
packages:
  Atelerix:
    path: ..
targets:
  LerixExample:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - LerixExample
    dependencies:
      - package: Atelerix
        product: Atelerix
    info:
      path: LerixExample/Info.plist
      properties:
        UILaunchScreen: {}
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UIBackgroundModes:
          - remote-notification
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: dev.atelerix.lerixexample
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGNING_REQUIRED: false
        CODE_SIGNING_ALLOWED: false
